<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-11-09 18:56
=======
# Generated by Django 4.2.7 on 2025-10-01 10:29
>>>>>>> 3068d61 (advanced filters, comments CRUD, and role-based permissions)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
=======
import uuid
>>>>>>> 3068d61 (advanced filters, comments CRUD, and role-based permissions)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_alter_asset_file_type'),
=======
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 3068d61 (advanced filters, comments CRUD, and role-based permissions)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('edit', 'Edit'), ('delete', 'Delete'), ('view', 'View')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='assets.asset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_ac_timesta_d54dbd_idx'), models.Index(fields=['user', '-timestamp'], name='activity_ac_user_id_d16f44_idx'), models.Index(fields=['asset', '-timestamp'], name='activity_ac_asset_i_65f463_idx')],
=======
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('edit', 'Edit'), ('delete', 'Delete'), ('view', 'View'), ('download', 'Download'), ('share', 'Share')], max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'action'], name='activity_lo_asset_i_1cae10_idx'), models.Index(fields=['user', 'timestamp'], name='activity_lo_user_id_e40ffe_idx'), models.Index(fields=['timestamp'], name='activity_lo_timesta_ef2c57_idx')],
>>>>>>> 3068d61 (advanced filters, comments CRUD, and role-based permissions)
            },
        ),
    ]
